### ISSUE TITLE
https://github.com/Roblox/cryo/ Not existing breaks the package

### ISSUE THREAD

**Issue by goldyydev** [vocksel/import#16]
When trying to install this module with Kayak/Rotriever the package fails to run correctly because it is missing Cryo, whose Github does not seem to exist
![image](https://user-images.githubusercontent.com/55450464/128635210-6f9e9824-652b-4826-9257-55d1e214a087.png)

This causes the following error in-game: 
![image](https://user-images.githubusercontent.com/55450464/128635225-acb5373a-bfa9-4383-bb20-bb2084a8f133.png)

**Comment by vocksel** [comment]
Ah, yeah. The Rotriever toml shouldn't even have Cryo or t as dependencies since I baked them into the source code. I'll remove those.

Keep an eye out for [Wally](https://github.com/UpliftGames/wally) by the way. I do not intend to support the Rotriever format once Wally allows public registry uploads, meaning that if Kayak does not update to support the `wally.toml` format you will not be able to install this library with it.

**Comment by goldyydev** [comment]
Yes, we've been planning on transitioning to Wally for a bit.

**Comment by unix-system** [comment]
Hopefully a rotriever.toml can still be present for a while; Wally looks great, but I don't think the stability (or functionality) is at par with even makeshift package managers like Kayak yet. Perhaps when Wally has better feature parity then rotriever.toml should get torpedoed?

**Comment by vocksel** [comment]
>when Wally has better feature parity 

Yeah, I won't remove rotriever.toml until either:
1. Kayak supports wally.toml, or
2. Wally reaches a point of stability and adoption that continuing to include rotriever.toml doesn't make sense

**Comment by vocksel** [comment]
@goldyydev I've tested this locally and have it working in #17. It would be a big help if you could verify this works on your end by modifying your `rotriever.toml` to include:
```
[dependencies]
import = { git = "https://github.com/vocksel/import", rev = "fix-kayak" }
```

**Comment by goldyydev** [comment]
Seems to be all working in my end!
